/**
 * Approximate fallback values for VSCode's Default Dark+ / Default Light+ themes.
 * Used by the base-theme toggle to simulate how unset keys "fall through" to
 * the user's active base theme — the gotcha documented in [CLAUDE.md](CLAUDE.md).
 *
 * Not a 1:1 copy of VSCode source; sampled from default themes to make
 * missing-key issues visually obvious.
 */
import { ALL_KEYS } from './keyRegistry';

const DARK: Record<string, string> = {
  foreground: '#CCCCCC',
  descriptionForeground: '#CCCCCCB3',
  disabledForeground: '#CCCCCC80',
  errorForeground: '#F48771',
  'icon.foreground': '#C5C5C5',
  focusBorder: '#007FD4',
  'selection.background': '#264F78',

  'titleBar.activeBackground': '#3C3C3C',
  'titleBar.activeForeground': '#CCCCCC',
  'titleBar.inactiveBackground': '#3C3C3C99',
  'titleBar.inactiveForeground': '#CCCCCC99',
  'titleBar.border': '#00000000',

  'activityBar.background': '#333333',
  'activityBar.foreground': '#FFFFFF',
  'activityBar.inactiveForeground': '#FFFFFF66',
  'activityBar.border': '#00000000',
  'activityBarBadge.background': '#007ACC',
  'activityBarBadge.foreground': '#FFFFFF',

  'sideBar.background': '#252526',
  'sideBar.foreground': '#CCCCCC',
  'sideBar.border': '#00000000',
  'sideBarTitle.foreground': '#BBBBBB',
  'sideBarSectionHeader.background': '#00000000',
  'sideBarSectionHeader.foreground': '#CCCCCC',
  'sideBarSectionHeader.border': '#CCCCCC33',

  'editor.background': '#1E1E1E',
  'editor.foreground': '#D4D4D4',
  'editorLineNumber.foreground': '#858585',
  'editorLineNumber.activeForeground': '#C6C6C6',
  'editor.lineHighlightBackground': '#FFFFFF0A',
  'editorCursor.foreground': '#AEAFAD',
  'editor.selectionBackground': '#264F78',
  'editor.selectionHighlightBackground': '#ADD6FF26',
  'editor.wordHighlightBackground': '#575757B8',
  'editor.wordHighlightStrongBackground': '#004972B8',
  'editor.findMatchBackground': '#515C6A',
  'editor.findMatchHighlightBackground': '#EA5C0055',
  'editorGroupHeader.tabsBackground': '#252526',
  'editorGroupHeader.tabsBorder': '#00000000',
  'editorGroupHeader.border': '#00000000',
  'editorIndentGuide.background1': '#404040',
  'editorIndentGuide.activeBackground1': '#707070',
  'editorBracketMatch.background': '#0064001A',
  'editorBracketMatch.border': '#888888',
  'editorGroup.border': '#444444',

  'tab.activeBackground': '#1E1E1E',
  'tab.activeForeground': '#FFFFFF',
  'tab.activeBorder': '#00000000',
  'tab.activeBorderTop': '#00000000',
  'tab.inactiveBackground': '#2D2D2D',
  'tab.inactiveForeground': '#FFFFFF80',
  'tab.border': '#252526',
  'tab.hoverBackground': '#1E1E1E',
  'tab.hoverForeground': '#FFFFFF',
  'tab.unfocusedActiveBorderTop': '#00000000',

  'panel.background': '#1E1E1E',
  'panel.border': '#80808059',
  'panelTitle.activeForeground': '#E7E7E7',
  'panelTitle.inactiveForeground': '#E7E7E799',
  'panelTitle.activeBorder': '#E7E7E7',

  'terminal.background': '#1E1E1E',
  'terminal.foreground': '#CCCCCC',
  terminalCursor: '#FFFFFF',
  'terminalCursor.foreground': '#FFFFFF',
  'terminal.ansiBlack': '#000000',
  'terminal.ansiRed': '#CD3131',
  'terminal.ansiGreen': '#0DBC79',
  'terminal.ansiYellow': '#E5E510',
  'terminal.ansiBlue': '#2472C8',
  'terminal.ansiMagenta': '#BC3FBC',
  'terminal.ansiCyan': '#11A8CD',
  'terminal.ansiWhite': '#E5E5E5',
  'terminal.ansiBrightBlack': '#666666',
  'terminal.ansiBrightRed': '#F14C4C',
  'terminal.ansiBrightGreen': '#23D18B',
  'terminal.ansiBrightYellow': '#F5F543',
  'terminal.ansiBrightBlue': '#3B8EEA',
  'terminal.ansiBrightMagenta': '#D670D6',
  'terminal.ansiBrightCyan': '#29B8DB',
  'terminal.ansiBrightWhite': '#E5E5E5',
  'terminal.ansiOrange': '#E5A00D',

  'statusBar.background': '#007ACC',
  'statusBar.foreground': '#FFFFFF',
  'statusBar.border': '#00000000',
  'statusBar.noFolderBackground': '#68217A',
  'statusBarItem.hoverBackground': '#FFFFFF1F',
  'statusBarItem.activeBackground': '#FFFFFF2E',

  'input.background': '#3C3C3C',
  'input.foreground': '#CCCCCC',
  'input.border': '#00000000',
  'input.placeholderForeground': '#CCCCCC80',
  'inputOption.activeBorder': '#007ACC',
  'inputValidation.errorBackground': '#5A1D1D',
  'inputValidation.errorBorder': '#BE1100',

  'dropdown.background': '#3C3C3C',
  'dropdown.foreground': '#F0F0F0',
  'dropdown.border': '#3C3C3C',

  'button.background': '#0E639C',
  'button.foreground': '#FFFFFF',
  'button.hoverBackground': '#1177BB',
  'button.secondaryBackground': '#3A3D41',
  'button.secondaryForeground': '#FFFFFF',
  'button.secondaryHoverBackground': '#45494E',

  'list.activeSelectionBackground': '#04395E',
  'list.activeSelectionForeground': '#FFFFFF',
  'list.inactiveSelectionBackground': '#37373D',
  'list.inactiveSelectionForeground': '#FFFFFF',
  'list.hoverBackground': '#2A2D2E',
  'list.hoverForeground': '#FFFFFF',
  'list.focusBackground': '#062F4A',
  'list.focusForeground': '#FFFFFF',
  'list.highlightForeground': '#2AAAFF',
  'list.dropBackground': '#062F4A',
  'list.inactiveFocusBackground': '#37373D',

  'editorWidget.background': '#252526',
  'editorWidget.foreground': '#CCCCCC',
  'editorWidget.border': '#454545',
  'editorSuggestWidget.background': '#252526',
  'editorSuggestWidget.foreground': '#D4D4D4',
  'editorSuggestWidget.border': '#454545',
  'editorSuggestWidget.selectedBackground': '#04395E',
  'editorSuggestWidget.highlightForeground': '#2AAAFF',
  'editorHoverWidget.background': '#252526',
  'editorHoverWidget.foreground': '#CCCCCC',
  'editorHoverWidget.border': '#454545',

  'notifications.background': '#252526',
  'notifications.foreground': '#CCCCCC',
  'notifications.border': '#303031',
  'notificationCenterHeader.background': '#303031',
  'notificationCenterHeader.foreground': '#CCCCCC',

  'menu.background': '#252526',
  'menu.foreground': '#CCCCCC',
  'menu.border': '#454545',
  'menu.selectionBackground': '#094771',
  'menu.selectionForeground': '#FFFFFF',
  'menu.separatorBackground': '#BBBBBB40',

  'breadcrumb.foreground': '#CCCCCCCC',
  'breadcrumb.background': '#1E1E1E',
  'breadcrumb.focusForeground': '#E0E0E0',
  'breadcrumb.activeSelectionForeground': '#E0E0E0',
  'breadcrumbPicker.background': '#252526',

  'textBlockQuote.background': '#7F7F7F1A',
  'textBlockQuote.border': '#007ACC80',
  'textCodeBlock.background': '#0A0A0A66',
  'textLink.foreground': '#3794FF',
  'textLink.activeForeground': '#3794FF',
  'textPreformat.foreground': '#D7BA7D',
  'textSeparator.foreground': '#FFFFFF2B',

  'peekView.border': '#007ACC',
  'peekViewEditor.background': '#001F33',
  'peekViewResult.background': '#252526',
  'peekViewResult.foreground': '#BBBBBB',
  'peekViewTitle.background': '#1E1E1E',
  'peekViewTitleLabel.foreground': '#FFFFFF',

  'gitDecoration.modifiedResourceForeground': '#E2C08D',
  'gitDecoration.deletedResourceForeground': '#C74E39',
  'gitDecoration.untrackedResourceForeground': '#73C991',
  'gitDecoration.ignoredResourceForeground': '#8C8C8C',
  'gitDecoration.conflictingResourceForeground': '#E4676B',

  'scrollbarSlider.background': '#79797966',
  'scrollbarSlider.hoverBackground': '#646464B3',
  'scrollbarSlider.activeBackground': '#BFBFBF66',
  'badge.background': '#4D4D4D',
  'badge.foreground': '#FFFFFF',

  'settings.headerForeground': '#E7E7E7',
  'settings.settingsHeaderHoverForeground': '#FFFFFF',
  'settings.modifiedItemIndicator': '#0C7D9D',
  'settings.dropdownForeground': '#F0F0F0',
  'settings.dropdownBackground': '#3C3C3C',
  'settings.dropdownBorder': '#3C3C3C',
  'settings.dropdownListBorder': '#454545',
  'settings.checkboxBackground': '#3C3C3C',
  'settings.checkboxForeground': '#F0F0F0',
  'settings.checkboxBorder': '#3C3C3C',
  'settings.rowHoverBackground': '#2A2D2E',
  'settings.textInputBackground': '#3C3C3C',
  'settings.textInputForeground': '#CCCCCC',
  'settings.textInputBorder': '#3C3C3C',
  'settings.numberInputBackground': '#3C3C3C',
  'settings.numberInputForeground': '#CCCCCC',
  'settings.numberInputBorder': '#3C3C3C',
  'settings.focusedRowBackground': '#2A2D2E',
  'settings.focusedRowBorder': '#007FD4',
  'settings.headerBorder': '#454545',
  'settings.sashBorder': '#454545',

  'checkbox.background': '#3C3C3C',
  'checkbox.foreground': '#F0F0F0',
  'checkbox.border': '#3C3C3C',
  'checkbox.selectBackground': '#007ACC',
  'checkbox.selectBorder': '#007ACC',

  'keybindingTable.headerBackground': '#252526',
  'keybindingTable.rowsBackground': '#1E1E1E',

  'quickInput.background': '#252526',
  'quickInput.foreground': '#CCCCCC',
  'quickInputTitle.background': '#303031',
  'pickerGroup.foreground': '#3794FF',
  'pickerGroup.border': '#3F3F46',

  'chat.requestBackground': '#2D2D30',
  'chat.requestBorder': '#454545',
  'chat.slashCommandBackground': '#34414B',
  'chat.slashCommandForeground': '#40A6FF',
  'chat.avatarBackground': '#1F6FEB',
  'chat.avatarForeground': '#FFFFFF',
  'chat.editedFileForeground': '#E2C08D',
  'symbolIcon.fileForeground': '#CCCCCC',
  'symbolIcon.folderForeground': '#C5C5C5',
};

const LIGHT: Record<string, string> = {
  foreground: '#3B3B3B',
  descriptionForeground: '#3B3B3BB3',
  disabledForeground: '#3B3B3B80',
  errorForeground: '#A1260D',
  'icon.foreground': '#424242',
  focusBorder: '#0090F1',
  'selection.background': '#ADD6FF',

  'titleBar.activeBackground': '#DDDDDD',
  'titleBar.activeForeground': '#333333',
  'titleBar.inactiveBackground': '#EEEEEE',
  'titleBar.inactiveForeground': '#33333399',
  'titleBar.border': '#00000000',

  'activityBar.background': '#F8F8F8',
  'activityBar.foreground': '#424242',
  'activityBar.inactiveForeground': '#42424266',
  'activityBar.border': '#00000000',
  'activityBarBadge.background': '#007ACC',
  'activityBarBadge.foreground': '#FFFFFF',

  'sideBar.background': '#F3F3F3',
  'sideBar.foreground': '#333333',
  'sideBar.border': '#00000000',
  'sideBarTitle.foreground': '#6F6F6F',
  'sideBarSectionHeader.background': '#00000000',
  'sideBarSectionHeader.foreground': '#333333',
  'sideBarSectionHeader.border': '#61616130',

  'editor.background': '#FFFFFF',
  'editor.foreground': '#000000',
  'editorLineNumber.foreground': '#237893',
  'editorLineNumber.activeForeground': '#0B216F',
  'editor.lineHighlightBackground': '#0000000A',
  'editorCursor.foreground': '#000000',
  'editor.selectionBackground': '#ADD6FF',
  'editor.selectionHighlightBackground': '#ADD6FF80',
  'editor.wordHighlightBackground': '#57575740',
  'editor.wordHighlightStrongBackground': '#0E639C40',
  'editor.findMatchBackground': '#A8AC94',
  'editor.findMatchHighlightBackground': '#EA5C0055',
  'editorGroupHeader.tabsBackground': '#F3F3F3',
  'editorGroupHeader.tabsBorder': '#00000000',
  'editorGroupHeader.border': '#00000000',
  'editorIndentGuide.background1': '#D3D3D3',
  'editorIndentGuide.activeBackground1': '#939393',
  'editorBracketMatch.background': '#0064001A',
  'editorBracketMatch.border': '#B9B9B9',
  'editorGroup.border': '#E7E7E7',

  'tab.activeBackground': '#FFFFFF',
  'tab.activeForeground': '#333333',
  'tab.activeBorder': '#00000000',
  'tab.activeBorderTop': '#00000000',
  'tab.inactiveBackground': '#ECECEC',
  'tab.inactiveForeground': '#333333B3',
  'tab.border': '#F3F3F3',
  'tab.hoverBackground': '#FFFFFF',
  'tab.hoverForeground': '#333333',
  'tab.unfocusedActiveBorderTop': '#00000000',

  'panel.background': '#FFFFFF',
  'panel.border': '#80808059',
  'panelTitle.activeForeground': '#424242',
  'panelTitle.inactiveForeground': '#42424299',
  'panelTitle.activeBorder': '#424242',

  'terminal.background': '#FFFFFF',
  'terminal.foreground': '#333333',
  'terminalCursor.foreground': '#333333',
  'terminal.ansiBlack': '#000000',
  'terminal.ansiRed': '#CD3131',
  'terminal.ansiGreen': '#00BC00',
  'terminal.ansiYellow': '#949800',
  'terminal.ansiBlue': '#0451A5',
  'terminal.ansiMagenta': '#BC05BC',
  'terminal.ansiCyan': '#0598BC',
  'terminal.ansiWhite': '#555555',
  'terminal.ansiBrightBlack': '#666666',
  'terminal.ansiBrightRed': '#CD3131',
  'terminal.ansiBrightGreen': '#14CE14',
  'terminal.ansiBrightYellow': '#B5BA00',
  'terminal.ansiBrightBlue': '#0451A5',
  'terminal.ansiBrightMagenta': '#BC05BC',
  'terminal.ansiBrightCyan': '#0598BC',
  'terminal.ansiBrightWhite': '#A5A5A5',
  'terminal.ansiOrange': '#C96A00',

  'statusBar.background': '#007ACC',
  'statusBar.foreground': '#FFFFFF',
  'statusBar.border': '#00000000',
  'statusBar.noFolderBackground': '#68217A',
  'statusBarItem.hoverBackground': '#FFFFFF1F',
  'statusBarItem.activeBackground': '#FFFFFF2E',

  'input.background': '#FFFFFF',
  'input.foreground': '#616161',
  'input.border': '#CECECE',
  'input.placeholderForeground': '#767676',
  'inputOption.activeBorder': '#007ACC',
  'inputValidation.errorBackground': '#F2DEDE',
  'inputValidation.errorBorder': '#BE1100',

  'dropdown.background': '#FFFFFF',
  'dropdown.foreground': '#616161',
  'dropdown.border': '#CECECE',

  'button.background': '#007ACC',
  'button.foreground': '#FFFFFF',
  'button.hoverBackground': '#0062A3',
  'button.secondaryBackground': '#5F6A79',
  'button.secondaryForeground': '#FFFFFF',
  'button.secondaryHoverBackground': '#4C5561',

  'list.activeSelectionBackground': '#0060C0',
  'list.activeSelectionForeground': '#FFFFFF',
  'list.inactiveSelectionBackground': '#E4E6F1',
  'list.inactiveSelectionForeground': '#000000',
  'list.hoverBackground': '#F0F0F0',
  'list.hoverForeground': '#000000',
  'list.focusBackground': '#D6EBFF',
  'list.focusForeground': '#000000',
  'list.highlightForeground': '#0066BF',
  'list.dropBackground': '#D6EBFF',
  'list.inactiveFocusBackground': '#D6EBFF',

  'editorWidget.background': '#F3F3F3',
  'editorWidget.foreground': '#333333',
  'editorWidget.border': '#C8C8C8',
  'editorSuggestWidget.background': '#F3F3F3',
  'editorSuggestWidget.foreground': '#000000',
  'editorSuggestWidget.border': '#C8C8C8',
  'editorSuggestWidget.selectedBackground': '#D6EBFF',
  'editorSuggestWidget.highlightForeground': '#0066BF',
  'editorHoverWidget.background': '#F3F3F3',
  'editorHoverWidget.foreground': '#333333',
  'editorHoverWidget.border': '#C8C8C8',

  'notifications.background': '#F3F3F3',
  'notifications.foreground': '#333333',
  'notifications.border': '#E5E5E5',
  'notificationCenterHeader.background': '#E5E5E5',
  'notificationCenterHeader.foreground': '#333333',

  'menu.background': '#FFFFFF',
  'menu.foreground': '#616161',
  'menu.border': '#D4D4D4',
  'menu.selectionBackground': '#0060C0',
  'menu.selectionForeground': '#FFFFFF',
  'menu.separatorBackground': '#D4D4D4',

  'breadcrumb.foreground': '#4E4E4E',
  'breadcrumb.background': '#FFFFFF',
  'breadcrumb.focusForeground': '#2B2B2B',
  'breadcrumb.activeSelectionForeground': '#2B2B2B',
  'breadcrumbPicker.background': '#F3F3F3',

  'textBlockQuote.background': '#7F7F7F1A',
  'textBlockQuote.border': '#007ACC80',
  'textCodeBlock.background': '#DCDCDC66',
  'textLink.foreground': '#006AB1',
  'textLink.activeForeground': '#006AB1',
  'textPreformat.foreground': '#A31515',
  'textSeparator.foreground': '#0000002B',

  'peekView.border': '#007ACC',
  'peekViewEditor.background': '#F2F8FC',
  'peekViewResult.background': '#F3F3F3',
  'peekViewResult.foreground': '#616161',
  'peekViewTitle.background': '#FFFFFF',
  'peekViewTitleLabel.foreground': '#333333',

  'gitDecoration.modifiedResourceForeground': '#895503',
  'gitDecoration.deletedResourceForeground': '#AD0707',
  'gitDecoration.untrackedResourceForeground': '#007100',
  'gitDecoration.ignoredResourceForeground': '#8E8E90',
  'gitDecoration.conflictingResourceForeground': '#AD0707',

  'scrollbarSlider.background': '#64646466',
  'scrollbarSlider.hoverBackground': '#646464B3',
  'scrollbarSlider.activeBackground': '#00000066',
  'badge.background': '#C4C4C4',
  'badge.foreground': '#333333',

  'settings.headerForeground': '#444444',
  'settings.settingsHeaderHoverForeground': '#2B2B2B',
  'settings.modifiedItemIndicator': '#0C7D9D',
  'settings.dropdownForeground': '#616161',
  'settings.dropdownBackground': '#FFFFFF',
  'settings.dropdownBorder': '#CECECE',
  'settings.dropdownListBorder': '#C8C8C8',
  'settings.checkboxBackground': '#FFFFFF',
  'settings.checkboxForeground': '#616161',
  'settings.checkboxBorder': '#CECECE',
  'settings.rowHoverBackground': '#F0F0F0',
  'settings.textInputBackground': '#FFFFFF',
  'settings.textInputForeground': '#616161',
  'settings.textInputBorder': '#CECECE',
  'settings.numberInputBackground': '#FFFFFF',
  'settings.numberInputForeground': '#616161',
  'settings.numberInputBorder': '#CECECE',
  'settings.focusedRowBackground': '#D6EBFF',
  'settings.focusedRowBorder': '#007FD4',
  'settings.headerBorder': '#C8C8C8',
  'settings.sashBorder': '#C8C8C8',

  'checkbox.background': '#FFFFFF',
  'checkbox.foreground': '#616161',
  'checkbox.border': '#CECECE',
  'checkbox.selectBackground': '#007ACC',
  'checkbox.selectBorder': '#007ACC',

  'keybindingTable.headerBackground': '#F3F3F3',
  'keybindingTable.rowsBackground': '#FFFFFF',

  'quickInput.background': '#F3F3F3',
  'quickInput.foreground': '#333333',
  'quickInputTitle.background': '#E5E5E5',
  'pickerGroup.foreground': '#0066BF',
  'pickerGroup.border': '#CCCEDB',

  'chat.requestBackground': '#F3F3F3',
  'chat.requestBorder': '#CECECE',
  'chat.slashCommandBackground': '#D9EAF8',
  'chat.slashCommandForeground': '#005FB8',
  'chat.avatarBackground': '#0060C0',
  'chat.avatarForeground': '#FFFFFF',
  'chat.editedFileForeground': '#895503',
  'symbolIcon.fileForeground': '#424242',
  'symbolIcon.folderForeground': '#545454',
};

function fill(base: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = { ...base };
  // Fill any registry key not covered above with a loud magenta sentinel so
  // missing entries in this fallback palette are obvious during development.
  for (const k of ALL_KEYS) if (!(k in out)) out[k] = '#FF00FF';
  return out;
}

export const BASE_PALETTES = {
  dark: fill(DARK),
  light: fill(LIGHT),
} as const;

export type BaseTheme = keyof typeof BASE_PALETTES;
