/**
 * Maps mockup component IDs to the color keys they consume.
 * Clicking a component opens a popover listing exactly these keys.
 * Every key in the registry that is visualizable in the mockup should appear
 * under at least one component id. Non-visualizable keys are reachable via
 * the "All keys" grid.
 */
export const COMPONENT_MAP: Record<string, readonly string[]> = {
  titleBar: [
    'titleBar.activeBackground',
    'titleBar.activeForeground',
    'titleBar.inactiveBackground',
    'titleBar.inactiveForeground',
    'titleBar.border',
  ],
  activityBar: [
    'activityBar.background',
    'activityBar.foreground',
    'activityBar.inactiveForeground',
    'activityBar.border',
    'activityBarBadge.background',
    'activityBarBadge.foreground',
    'badge.background',
    'badge.foreground',
  ],
  sideBar: [
    'sideBar.background',
    'sideBar.foreground',
    'sideBar.border',
    'sideBarTitle.foreground',
    'sideBarSectionHeader.background',
    'sideBarSectionHeader.foreground',
    'sideBarSectionHeader.border',
    'list.activeSelectionBackground',
    'list.activeSelectionForeground',
    'list.inactiveSelectionBackground',
    'list.inactiveSelectionForeground',
    'list.hoverBackground',
    'list.hoverForeground',
    'list.focusBackground',
    'list.focusForeground',
    'list.highlightForeground',
    'list.dropBackground',
    'list.inactiveFocusBackground',
    'gitDecoration.modifiedResourceForeground',
    'gitDecoration.deletedResourceForeground',
    'gitDecoration.untrackedResourceForeground',
    'gitDecoration.ignoredResourceForeground',
    'gitDecoration.conflictingResourceForeground',
    'focusBorder',
    'icon.foreground',
  ],
  breadcrumb: [
    'breadcrumb.background',
    'breadcrumb.foreground',
    'breadcrumb.focusForeground',
    'breadcrumb.activeSelectionForeground',
    'breadcrumbPicker.background',
  ],
  editor: [
    'editor.background',
    'editor.foreground',
    'foreground',
    'descriptionForeground',
    'disabledForeground',
    'errorForeground',
    'selection.background',
    'editor.lineHighlightBackground',
    'editor.selectionBackground',
    'editor.selectionHighlightBackground',
    'editor.wordHighlightBackground',
    'editor.wordHighlightStrongBackground',
    'editor.findMatchBackground',
    'editor.findMatchHighlightBackground',
    'editorCursor.foreground',
    'editorLineNumber.foreground',
    'editorLineNumber.activeForeground',
    'editorIndentGuide.background1',
    'editorIndentGuide.activeBackground1',
    'editorBracketMatch.background',
    'editorBracketMatch.border',
    'editorGroup.border',
    'scrollbarSlider.background',
    'scrollbarSlider.hoverBackground',
    'scrollbarSlider.activeBackground',
    'textBlockQuote.background',
    'textBlockQuote.border',
    'textCodeBlock.background',
    'textLink.foreground',
    'textLink.activeForeground',
    'textPreformat.foreground',
    'textSeparator.foreground',
  ],
  tabs: [
    'editorGroupHeader.tabsBackground',
    'editorGroupHeader.tabsBorder',
    'editorGroupHeader.border',
    'tab.activeBackground',
    'tab.activeForeground',
    'tab.activeBorder',
    'tab.activeBorderTop',
    'tab.inactiveBackground',
    'tab.inactiveForeground',
    'tab.border',
    'tab.hoverBackground',
    'tab.hoverForeground',
    'tab.unfocusedActiveBorderTop',
  ],
  hoverWidget: [
    'editorHoverWidget.background',
    'editorHoverWidget.foreground',
    'editorHoverWidget.border',
    'editorWidget.background',
    'editorWidget.foreground',
    'editorWidget.border',
  ],
  suggestWidget: [
    'editorSuggestWidget.background',
    'editorSuggestWidget.foreground',
    'editorSuggestWidget.border',
    'editorSuggestWidget.selectedBackground',
    'editorSuggestWidget.highlightForeground',
  ],
  panel: [
    'panel.background',
    'panel.border',
    'panelTitle.activeForeground',
    'panelTitle.inactiveForeground',
    'panelTitle.activeBorder',
  ],
  terminal: [
    'terminal.background',
    'terminal.foreground',
    'terminalCursor.foreground',
    'terminal.ansiBlack',
    'terminal.ansiBrightBlack',
    'terminal.ansiRed',
    'terminal.ansiBrightRed',
    'terminal.ansiGreen',
    'terminal.ansiBrightGreen',
    'terminal.ansiYellow',
    'terminal.ansiBrightYellow',
    'terminal.ansiBlue',
    'terminal.ansiBrightBlue',
    'terminal.ansiMagenta',
    'terminal.ansiBrightMagenta',
    'terminal.ansiCyan',
    'terminal.ansiBrightCyan',
    'terminal.ansiWhite',
    'terminal.ansiBrightWhite',
    'terminal.ansiOrange',
  ],
  statusBar: [
    'statusBar.background',
    'statusBar.foreground',
    'statusBar.border',
    'statusBar.noFolderBackground',
    'statusBarItem.hoverBackground',
    'statusBarItem.activeBackground',
  ],
  commandPalette: [
    'quickInput.background',
    'quickInput.foreground',
    'quickInputTitle.background',
    'pickerGroup.foreground',
    'pickerGroup.border',
    'input.background',
    'input.foreground',
    'input.border',
    'input.placeholderForeground',
    'inputOption.activeBorder',
    'inputValidation.errorBackground',
    'inputValidation.errorBorder',
  ],
  settingsPage: [
    'settings.headerForeground',
    'settings.settingsHeaderHoverForeground',
    'settings.modifiedItemIndicator',
    'settings.dropdownForeground',
    'settings.dropdownBackground',
    'settings.dropdownBorder',
    'settings.dropdownListBorder',
    'settings.checkboxBackground',
    'settings.checkboxForeground',
    'settings.checkboxBorder',
    'settings.rowHoverBackground',
    'settings.textInputBackground',
    'settings.textInputForeground',
    'settings.textInputBorder',
    'settings.numberInputBackground',
    'settings.numberInputForeground',
    'settings.numberInputBorder',
    'settings.focusedRowBackground',
    'settings.focusedRowBorder',
    'settings.headerBorder',
    'settings.sashBorder',
    'checkbox.background',
    'checkbox.foreground',
    'checkbox.border',
    'checkbox.selectBackground',
    'checkbox.selectBorder',
    'keybindingTable.headerBackground',
    'keybindingTable.rowsBackground',
    'dropdown.background',
    'dropdown.foreground',
    'dropdown.border',
    'button.background',
    'button.foreground',
    'button.hoverBackground',
    'button.secondaryBackground',
    'button.secondaryForeground',
    'button.secondaryHoverBackground',
  ],
  chat: [
    'chat.requestBackground',
    'chat.requestBorder',
    'chat.slashCommandBackground',
    'chat.slashCommandForeground',
    'chat.avatarBackground',
    'chat.avatarForeground',
    'chat.editedFileForeground',
    'symbolIcon.fileForeground',
    'symbolIcon.folderForeground',
  ],
  notifications: [
    'notifications.background',
    'notifications.foreground',
    'notifications.border',
    'notificationCenterHeader.background',
    'notificationCenterHeader.foreground',
  ],
  menu: [
    'menu.background',
    'menu.foreground',
    'menu.border',
    'menu.selectionBackground',
    'menu.selectionForeground',
    'menu.separatorBackground',
  ],
  peekView: [
    'peekView.border',
    'peekViewEditor.background',
    'peekViewResult.background',
    'peekViewResult.foreground',
    'peekViewTitle.background',
    'peekViewTitleLabel.foreground',
  ],
};

export type ComponentId = keyof typeof COMPONENT_MAP;
